### ISSUE TITLE
[Duda] Código HCaptcha.

### ISSUE THREAD

**Issue by ZeroCool22** [LaDevWendy/rouzer3.0#2]
![Screenshot_5](https://user-images.githubusercontent.com/13344308/144723989-89b1ef94-a7c2-4fce-bbce-eef9ef0464dd.jpg)

Esta correctamente agregado el código de HCaptcha o hay alguna coma o llave de más?

Gracias.

**Comment by LaDevWendy** [comment]
Las claves de HCaptcha van en WebApp/appsettings.Production.json
Vos las pusiste en WebApp/appsettings.json

**Comment by ZeroCool22** [comment]
> Las claves de HCaptcha van en WebApp/appsettings.Production.json Vos las pusiste en WebApp/appsettings.json

Gracias, momento de retraso mio.

**Comment by ZeroCool22** [comment]
Las puse donde correspondía...

El Captcha aparece, pero aunque se lo soluciones correctamente falla.

En la Consola sale esto:

![Screenshot_6](https://user-images.githubusercontent.com/13344308/144729570-5d0da1ce-8c64-43ba-a276-cccec5f4144f.png)

**Comment by ZeroCool22** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/13344308/144729934-68c594d2-59a0-46a0-b7ed-3684662c8db0.jpg)

**Comment by ZeroCool22** [comment]
Creo que es una opción de CF que todavía no puedo configurar por cuestiones de acceso, apenas la pueda activar confirmo si se solucionó.

**Comment by ZeroCool22** [comment]
✅ Todo solucionado, era por parte de CF.
