### ISSUE TITLE
Configuración de Cloudflare (creo) hace que el contador Online de users se bugee?

### ISSUE THREAD

**Issue by ZeroCool22** [LaDevWendy/rouzer3.0#4]
La web funciona bien, pero el **Contador Online** de users se bugea, llega  un x número y se queda ahí, **si actualizo la página puedo ver por un instante los usuarios reales conectados**, pero a los 2-3 segundos vuelve a mostrar el número "bugeado".

Sospecho que sea alguna config de CF sobre **el Cache** dejo una screenshot si es de ayuda...

![screenshot-dash cloudflare com-2021 12 05-22_18_40](https://user-images.githubusercontent.com/13344308/144773622-5ea62d10-f5e9-4536-b445-c3446eba0ea4.png)

![Tiered caching](https://user-images.githubusercontent.com/13344308/144773792-d3d023c4-8274-413b-b12f-f535058105d5.png)

**Comment by LaDevWendy** [comment]
Las estadísticas están guardadas en el archivo rozed/WebApp/estadisticas.json, y este archivo se actualiza cada vez que se crea un comentario o un hilo. Cada un segundo se lee este archivo, y entre 0 y 6 segundos se actualiza el visor en la página con los datos tomados ahí.
Al cargar la página se muestra la cantidad de conectados en ese instante, para luego pasar a mostrar la cantidad de conectados guardada en el archivo json. Si no se han creado hilos o comentarios la cantidad de conectados va a ser 0, porque ese valor nunca se actualizó en el archivo.
En el funcionamiento normal de la página no genera muchos problemas, con poca actividad todavía hay alrededor de 5 comentarios por minuto que mantienen actualizado el archivo json. Pero si querés más precisión podés cambiar el archivo WebApp\Servicios\EstadisticasService.cs en sus líneas 37 a 44 para que quede así:

Task.Run(async () => {
    while (true)
    {
        estadisticas = JsonSerializer.Deserialize<Estadisticas>(await File.ReadAllTextAsync(ubicacionDeArchivo));
        estadisticas = await GetEstadisticasAsync();
        await Task.Delay(1000);
    }
});

De esta forma toma las estadísticas del archivo y luego actualiza la cantidad de conectados al valor actual.

**Comment by ZeroCool22** [comment]
Perfecto, esa era mi duda, yo pensé que se actualizaba solo (sin que se hiciera click o creara un Roz), ahora me queda más claro como funciona.

**Comment by ZeroCool22** [comment]
Te lo pregunto acá para no abrir otro tema.

Se puede modificar el código de alguna forma para que los **MODS** no puedan banear a un **ADMIN**?

Si nos guiamos por la Jerarquía un MOD no debería poder banear a un ADMIN, pero no sé si está hecho así por algún tema en particular...

**Comment by LaDevWendy** [comment]
Puede ser agregando esto a partir de la línea 270 de rozed/WebApp/Controllers/Api/ModeracionController.cs

var admins = await userManager.GetUsersForClaimAsync(new Claim("Role", "admin")); // Busca todos los admins
var adm = admins.FirstOrDefault(a => a.Id == (tipo == TipoElemento.Comentario ? comentario.UsuarioId : hilo.UsuarioId)); // Busca el que tenga el Id que está siendo baneado
if (adm != null) // Si encuentra un admin con ese Id...
{
    if (!User.EsAdmin()) // pregunta si el que hace el baneo es otro admin...
    {
        return Json(new ApiResponse("Error: un admin no puede ser baneado por uno de menor rango")); // si no lo es envía error
    }
}

no lo probé así que no sé si funciona, pero algo así debería ser.

**Comment by ZeroCool22** [comment]
> Puede ser agregando esto a partir de la línea 270 de rozed/WebApp/Controllers/Api/ModeracionController.cs
> 
> var admins = await userManager.GetUsersForClaimAsync(new Claim("Role", "admin")); // Busca todos los admins var adm = admins.FirstOrDefault(a => a.Id == (tipo == TipoElemento.Comentario ? comentario.UsuarioId : hilo.UsuarioId)); // Busca el que tenga el Id que está siendo baneado if (adm != null) // Si encuentra un admin con ese Id... { if (!User.EsAdmin()) // pregunta si el que hace el baneo es otro admin... { return Json(new ApiResponse("Error: un admin no puede ser baneado por uno de menor rango")); // si no lo es envía error } }
> 
> no lo probé así que no sé si funciona, pero algo así debería ser.

Buenísimo, voy a probarlo. Gracias.

**Comment by ZeroCool22** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/13344308/145055652-f7f54f8a-5482-4fbf-938a-8fc1331f7c8b.jpg)

Agregue el código, pero los MODS siguen pudiendo banear ADMINS.

*No es la linea 270 exacta, pero es porque no estoy usando la última versión.

**Comment by LaDevWendy** [comment]
Lo probé y me funciona. No se baneó ni se borró el roz.
![Sin título](https://user-images.githubusercontent.com/94111185/145063701-c799b708-2b29-4177-8cb9-c91b714879db.png)

**Comment by ZeroCool22** [comment]
> Lo probé y me funciona. No se baneó ni se borró el roz. ![Sin título](https://user-images.githubusercontent.com/94111185/145063701-c799b708-2b29-4177-8cb9-c91b714879db.png)

Te mandé un mensaje al correo que tenés registrado en GH, (protonmail).
