### ISSUE TITLE
[Request] Poder embeber links de videos .MP4.

### ISSUE THREAD

**Issue by ZeroCool22** [LaDevWendy/rouzer3.0#5]
Quería preguntarte si es posible hacer que se puedan embeber links de videos por ej: www.video.com/muestra.mp4

Como se puede hacer en esta web: 

https://onelineplayer.com/

Pones el link de un video terminado con la extensión .MP4 por ej, y lo podés ver online.

Saludos.

**Comment by LaDevWendy** [comment]
¿En comentarios o en hilos? En los hilos los admins tienen la opción de habilitar markdown (con el comando >>md). Markdown por defecto puede interpretar html aunque Rozed lo desactiva, línea 27 de este archivo:
[Formateador.cs](https://github.com/LaDevWendy/rouzer3.0/blob/main/Servicios/Formateador.cs)
si sacás esa línea se puede usar html dentro del contenido del hilo. Ya he probado embeber contenido y funciona.

Si querés embeber en las portadas hay que crear nuevos tipos de "medias". Para crear nuevos "medias" hay que trabajar en estos archivos:
[MediaModel](https://github.com/LaDevWendy/rouzer3.0/blob/main/Modelos/MediaModel.cs)
[MediaService](https://github.com/LaDevWendy/rouzer3.0/blob/main/WebApp/Properties/MediaService.cs)
[Media.svelte](https://github.com/LaDevWendy/rouzer3.0/blob/main/FrontEndWeb/src/components/Media.svelte)
[MediaInput.svelte](https://github.com/LaDevWendy/rouzer3.0/blob/main/FrontEndWeb/src/components/MediaInput.svelte)
se pueden usar los ya desarrollados como ejemplo (youtube, bitchute, pornhub, dailymotion).
